TheSims/Controllers/DomesticUnitController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TheSims.Models;

namespace TheSims.Controllers
{
    public class DomesticUnitController : Controller
    {
        private IRepository repository;
        public DomesticUnitController(IRepository repo)
        {
            repository = repo;
        }

        public ActionResult List() => View(repository.DomesticUnits);
    }
}

TheSims/Controllers/SimController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TheSims.Models;
using TheSims.Models.ViewModels;

namespace TheSims.Controllers
{
    public class SimController : Controller
    {
        private IRepository repository;
        public SimController(IRepository repo)
        {
            repository = repo;
        }

        public ViewResult Profile(int id) => View(
            repository.Sims
            .FirstOrDefault(s => s.SimID == id));        

        public ViewResult FilterForm()
        {
            var professions = repository.Professions;
            SimSearchFilterForm form = new SimSearchFilterForm
            {
                Professions = professions
            };
            return View(form);
        }

        public ActionResult List(SimSearchFilterForm form) =>
            View(repository.Sims
                .Where(s =>
                (form.Sim.Name != null && form.Sim.Name == s.Name) || (form.Sim.Name == null && s.Name != null))
                .Where(s =>
                (form.Sim.LastName != null && form.Sim.LastName == s.LastName) || (form.Sim.LastName == null && s.LastName != null))
                );

        //ADMIN
        public ViewResult Index() => View(repository.Sims);
        public ViewResult Edit(int simID) =>
           View(repository.Sims
               .FirstOrDefault(s => s.SimID == simID));

        [HttpPost]
        public IActionResult Edit(Sim sim)
        {

            if (ModelState.IsValid)
            {
                repository.SaveSim(sim);
                TempData["message"] = $"{sim.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(sim);
            }
        }
        public ViewResult Create() => View("Edit", new Sim());

        [HttpPost]
        public IActionResult Delete(int simID)
        {
            Sim deletedSim = repository.DeleteSim(simID);
            if (deletedSim != null)
            {
                TempData["message"] = $"{deletedSim.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

TheSims/Views/Shared/_AdminLayout.cshtml
    <!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cosmo.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <title>@ViewBag.Title</title>
        <style>
            .input-validation-error {
                border-color: red;
                background-color: #fee;
            }
        </style>
        <script src="/lib/jquery/dist/jquery.js"></script>
        <script src="/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js">
        </script>
    </head>
    <body class="m-1 p-1">
        <div class="bg-info p-2"><h4>@ViewBag.Title</h4></div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </body>
    </html>

TheSims/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Sims</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cosmo.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">


            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Sim" asp-action="FilterForm">Sims</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="DomesticUnit" asp-action="List">Domestic Unit</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Consult</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="" asp-controller="Sim" asp-action="FilterForm">Sims</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - The Sims
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>